upstream rails_puma {
  server 127.0.0.1:3000 fail_timeout=0;
}

server {
  listen 80;
  server_name shengfukung.com.tw www.shengfukung.com.tw;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name shengfukung.com.tw www.shengfukung.com.tw;

  ssl_certificate /etc/letsencrypt/live/shengfukung.com.tw/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/shengfukung.com.tw/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  root /var/www/shengfukung-wenfu;

  location /.well-known/ { try_files $uri $uri/ =404; }
  location ^~ /frontend/assets/ { try_files $uri $uri/ =404; }

  location ^~ /backend/assets/ {
    alias /home/jimmy1768_user/Projects/shengfukung-wenfu/rails/public/backend/assets/;
    try_files $uri =404;
  }

  location ^~ /assets/ {
    alias /home/jimmy1768_user/Projects/shengfukung-wenfu/rails/public/backend/assets/;
    try_files $uri =404;
  }

  location ^~ /marketing/admin {
    proxy_pass http://rails_puma;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ^~ /admin {
    proxy_pass http://rails_puma;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ^~ /account {
    proxy_pass http://rails_puma;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ^~ /dev {
    proxy_pass http://rails_puma;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ^~ /api {
    proxy_pass http://rails_puma;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / { try_files $uri $uri/ /index.html; }
}
