upstream rails_puma {
  server 127.0.0.1:3000 fail_timeout=0;
}

server {
  server_name shengfukung.com.tw www.shengfukung.com.tw;
  root /var/www/shengfukung-wenfu;

  location /.well-known/ {
    try_files $uri $uri/ =404;
  }

  location ^~ /marketing-assets/ {
    try_files $uri $uri/ =404;
  }

  location ^~ /marketing/admin {
    proxy_pass http://rails_puma;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ^~ /admin {
    proxy_pass http://rails_puma;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location ^~ /api {
    proxy_pass http://rails_puma;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/shengfukung.com.tw/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/shengfukung.com.tw/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}


server {
    if ($host = www.shengfukung.com.tw) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = shengfukung.com.tw) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  server_name shengfukung.com.tw www.shengfukung.com.tw;
    return 404; # managed by Certbot




}