export const copy = {
  'zh-TW': {
    appName: 'TempleMate', loading: '正在準備示範帳戶…', loadingRelease: '正在載入…',
    signIn: '登入', signOut: '登出', signInPrompt: '以示範帳戶登入', email: '電子郵件', password: '密碼', name: '姓名', nativeName: '中文姓名', englishName: '英文姓名', phone: '電話', city: '居住區', relationship: '關係',
    home: '首頁', profile: '個人資料', dependents: '家屬', registrations: '登記', discover: '探索', settings: '設定', save: '儲存', add: '新增', update: '更新', delete: '刪除', retry: '再試一次', back: '返回',
    createAccount: '建立帳號', forgotPassword: '忘記密碼', fixtureCredentials: '示範帳號：member@example.test　密碼：templemate-demo', recoveryNotice: '此示範不會寄送電子郵件。', recoveryNoticeRelease: '請輸入註冊時使用的電子郵件地址。', signupNotice: '帳號建立將在未來安全帳戶服務啟用後提供。', googleSignIn: '以 Google 登入', appleSignIn: '以 Apple 登入', realAccount: '本機／測試帳戶模式：僅使用宮廟帳戶服務與系統瀏覽器。', realAccountRelease: '使用宮廟帳戶服務與系統瀏覽器登入。', oauthBrowserNotice: '登入會在系統瀏覽器完成；此 App 不保留提供者憑證。', oauthResolutionIntro: '此登入方式尚未連結任何帳戶。', oauthResolutionExisting: '我已經有帳戶', oauthResolutionExistingDescription: '登入以將此方式連結到您的帳戶。', oauthResolutionNew: '建立新帳戶', oauthResolutionNewDescription: '提供您的資料並接受條款以繼續。', oauthResolutionLink: '連結帳戶', oauthResolutionCreate: '建立帳戶', termsAccept: '我接受目前的服務條款。', oauthOutcome: { idle: '尚未開始外部登入。', pending: '正在準備安全登入…', browser_opened: '系統瀏覽器已開啟。', returned: '已安全接收返回。', exchanging: '正在完成登入…', authenticated: '登入完成。', profile_required: '請補齊帳戶資料。', cancelled: '登入已取消。', denied: '登入授權被拒絕。', failed: '外部登入未完成，請重新開始。', invalid: '返回無效，已安全清除登入狀態。', expired: '登入已過期，請重新開始。', interrupted: '登入被中斷；請重新開始。', closed: '此帳戶已關閉。' },
    account: '帳戶', templeConnection: '宮廟連結', connected: '已連結', notConnected: '尚未連結', setupTemple: '完成宮廟設定', setupTempleDescription: '請掃描您的宮廟 QR code 以完成設定。', realBindingUnavailable: '此本機／測試帳戶目前無法使用宮廟 QR 綁定。您可以安全登出。', connectionLink: 'TempleMate 連結', connectWithLink: '使用連結連結', scanDemoCode: '掃描示範 QR', scanCodeRelease: '掃描宮廟 QR', cameraPermissionLoading: '正在確認相機權限…', cameraPermissionDenied: '需要相機權限才能掃描示範 QR。', cameraPermissionBlocked: '相機權限已關閉；請在裝置設定中允許 TempleMate 使用相機。', cameraPermissionRetry: '要求相機權限', cameraInstructions: '將示範宮廟 QR 放入框內。', cameraInstructionsRelease: '請將宮廟 QR code 放入框內。', cameraCancel: '取消掃描', cameraTryAgain: '再掃一次', cameraInvalidQr: '此 QR 不是受信任的示範宮廟連結。尚未變更宮廟連結。', cameraInvalidQrRelease: '此 QR 不是受信任的宮廟連結。尚未變更宮廟連結。', cameraValidating: '正在安全確認 QR…', unbindTemple: '解除宮廟連結', unbindTempleDescription: '解除後需要重新掃描宮廟 QR code 才能使用。', switchTemple: '切換宮廟', switchDescription: '確認後會清除先前宮廟的登入、快取與待處理示範資料。', confirmSwitch: '確認並切換',
    certificates: '證明文件', certificateFixture: '平安祈福參與證明', appearance: '外觀', language: '語言', light: '淺色', dark: '深色', privacyHelp: '隱私與協助', assistance: '協助', assistanceDescription: '向宮廟工作人員的協助佇列提出請求。', assistanceDestination: '此請求會送往宮廟工作人員的協助佇列；不會宣稱電子郵件或收件匣送達。', assistanceFixture: '示範模式：此請求只會保留在本機 fixture，不會送給工作人員。', assistanceCreated: '協助請求已建立。', assistanceDuplicate: '已有處理中的協助請求。', assistanceFixtureSubmitted: '示範協助請求已保留在本機。', privacyRequest: '隱私請求', exportData: '匯出資料', deletionRequest: '刪除請求', closeAccount: '關閉帳戶', closeDescription: '輸入 CLOSE 以確認示範帳戶關閉。', closeDescriptionRelease: '輸入 CLOSE 以確認關閉帳戶。', resetDemo: '重設示範資料', message: '訊息', send: '送出', offering: '項目', registrant: '登記人', quantity: '數量', contactName: '聯絡姓名', householdNotes: '家戶備註', arrivalWindow: '抵達時段', ceremonyNotes: '儀式備註', register: '登記', createRegistration: '建立登記', cancel: '取消', discoverOfferings: '前往探索項目', registrationDiscoverHint: '請從宮廟提供的項目開始登記。', alreadyRegistered: '此項目您已完成登記，若需協助請洽宮廟服務台。', draft: '草稿', paidReadOnly: '已完成（僅供展示，不能修改）', stageAwaitingAdminCompletion: '已收到您的登記，宮廟正在處理中。', stageBlockedOnBilling: '已收到您的登記，宮廟正在處理中。', stageAwaitingPayment: '待完成付款。', stageAwaitingFulfilment: '宮廟正在安排中。', stageFulfilled: '已完成。', stageCancelled: '已取消。', pendingCashArrangement: '線上付款目前無法使用；請與宮廟安排現金付款。', completedCashDemo: '已完成現金（示範資料，僅供展示，不能修改）', saved: '已儲存', welcome: '您好，', activity: '活動', services: '服務', gallery: '相簿', photos: '張照片', emptyAlbum: '此相簿尚無照片。', closePhoto: '關閉', previousPhoto: '上一張', nextPhoto: '下一張', emptyDependents: '尚未加入家屬。', emptyRegistrations: '尚未建立登記。', emptyCertificates: '尚無證明文件。', emptyCollection: '目前沒有資料。', collectionFailed: '資料載入失敗，請稍後再試。', notFound: '找不到頁面', notFoundDescription: '此頁面無法使用，已安全保留您的帳戶資料。', bindingFailed: '連結失敗，請檢查示範連結後再試一次。'
  },
  en: {
    appName: 'TempleMate', loading: 'Preparing the demo account…', loadingRelease: 'Loading…',
    signIn: 'Sign in', signOut: 'Sign out', signInPrompt: 'Sign in with the demo account', email: 'Email', password: 'Password', name: 'Name', nativeName: 'Name (Chinese)', englishName: 'Name (English)', phone: 'Phone', city: 'City/Region', relationship: 'Relationship',
    home: 'Home', profile: 'Profile', dependents: 'Dependents', registrations: 'Registrations', discover: 'Explore', settings: 'Settings', save: 'Save', add: 'Add', update: 'Update', delete: 'Delete', retry: 'Try again', back: 'Back',
    createAccount: 'Create account', forgotPassword: 'Forgot password', fixtureCredentials: 'Demo account: member@example.test  Password: templemate-demo', recoveryNotice: 'This demo does not send email.', recoveryNoticeRelease: 'Enter the email address you registered with.', signupNotice: 'Account creation will be available with a future secure account service.', googleSignIn: 'Continue with Google', appleSignIn: 'Continue with Apple', realAccount: 'Local/test account mode: only the temple account service and system browser are used.', realAccountRelease: 'Sign in using the temple account service and system browser.', oauthBrowserNotice: 'Sign-in completes in the system browser; this app does not retain provider credentials.', oauthResolutionIntro: "This sign-in method isn't linked to an account yet.", oauthResolutionExisting: 'I already have an account', oauthResolutionExistingDescription: 'Sign in to link this method to your account.', oauthResolutionNew: 'Create a new account', oauthResolutionNewDescription: 'Provide your details and accept the terms to continue.', oauthResolutionLink: 'Link account', oauthResolutionCreate: 'Create account', termsAccept: 'I accept the current terms.', oauthOutcome: { idle: 'External sign-in has not started.', pending: 'Preparing secure sign-in…', browser_opened: 'System browser is open.', returned: 'Secure return received.', exchanging: 'Completing sign-in…', authenticated: 'Signed in.', profile_required: 'Complete your account profile.', cancelled: 'Sign-in was cancelled.', denied: 'Sign-in permission was denied.', failed: 'External sign-in did not complete. Start again.', invalid: 'The return was invalid and sign-in state was safely cleared.', expired: 'Sign-in expired. Start again.', interrupted: 'Sign-in was interrupted; start again.', closed: 'This account is closed.' },
    account: 'Account', templeConnection: 'Temple connection', connected: 'Connected', notConnected: 'Not connected', setupTemple: 'Finish temple setup', setupTempleDescription: 'Scan your temple QR code to finish setup.', realBindingUnavailable: 'Temple QR binding is unavailable for this local/test account. You can safely sign out.', connectionLink: 'TempleMate connection link', connectWithLink: 'Connect with link', scanDemoCode: 'Scan demo QR', scanCodeRelease: 'Scan temple QR', cameraPermissionLoading: 'Checking camera permission…', cameraPermissionDenied: 'Camera permission is needed to scan a demo QR code.', cameraPermissionBlocked: 'Camera permission is off. Allow TempleMate camera access in device settings.', cameraPermissionRetry: 'Request camera permission', cameraInstructions: 'Place the demo temple QR code inside the frame.', cameraInstructionsRelease: 'Place the temple QR code inside the frame.', cameraCancel: 'Cancel scan', cameraTryAgain: 'Scan again', cameraInvalidQr: 'This QR is not a trusted demo temple link. Your temple connection was not changed.', cameraInvalidQrRelease: 'This QR is not a trusted temple link. Your temple connection was not changed.', cameraValidating: 'Confirming the QR safely…', unbindTemple: 'Unbind temple', unbindTempleDescription: 'You will need to scan the temple QR code again.', switchTemple: 'Switch temple', switchDescription: 'Confirmation clears the previous temple’s sign-in, cache, and pending demo data.', confirmSwitch: 'Confirm switch',
    certificates: 'Certificates', certificateFixture: 'Peace blessing participation certificate', appearance: 'Appearance', language: 'Language', light: 'Light', dark: 'Dark', privacyHelp: 'Privacy & help', assistance: 'Assistance', assistanceDescription: 'Request help from temple staff through the assistance queue.', assistanceDestination: 'This request goes to the temple staff assistance queue; it does not claim email or inbox delivery.', assistanceFixture: 'Demo mode: this request stays in the local fixture and is not delivered to temple staff.', assistanceCreated: 'Assistance request created.', assistanceDuplicate: 'An assistance request is already open.', assistanceFixtureSubmitted: 'Demo assistance request retained locally.', privacyRequest: 'Privacy request', exportData: 'Export data', deletionRequest: 'Deletion request', closeAccount: 'Close account', closeDescription: 'Enter CLOSE to confirm closing this demo account.', closeDescriptionRelease: 'Enter CLOSE to confirm closing your account.', resetDemo: 'Reset demo data', message: 'Message', send: 'Send', offering: 'Offering', registrant: 'Registrant', quantity: 'Quantity', contactName: 'Contact name', householdNotes: 'Household notes', arrivalWindow: 'Arrival window', ceremonyNotes: 'Ceremony notes', register: 'Register', createRegistration: 'Create registration', cancel: 'Cancel', discoverOfferings: 'Browse temple offerings', registrationDiscoverHint: 'Start from an offering provided by this temple.', alreadyRegistered: 'You are already registered for this. Contact the temple desk if you need help.', draft: 'Draft', paidReadOnly: 'Completed (display only; cannot be edited)', stageAwaitingAdminCompletion: "We've received your registration. The temple is processing it.", stageBlockedOnBilling: "We've received your registration. The temple is processing it.", stageAwaitingPayment: 'Awaiting payment.', stageAwaitingFulfilment: 'The temple is preparing your registration.', stageFulfilled: 'Completed.', stageCancelled: 'Cancelled.', pendingCashArrangement: 'Online payment is unavailable. Arrange cash payment with the temple.', completedCashDemo: 'Cash completed (demo data; display only and cannot be edited)', saved: 'Saved', welcome: 'Hello, ', activity: 'Events', services: 'Services', gallery: 'Gallery', photos: 'photos', emptyAlbum: 'This album has no photos yet.', closePhoto: 'Close', previousPhoto: 'Previous', nextPhoto: 'Next', emptyDependents: 'No dependents yet.', emptyRegistrations: 'No registrations yet.', emptyCertificates: 'No certificates yet.', emptyCollection: 'No records yet.', collectionFailed: 'Unable to load account records. Try again later.', notFound: 'Page unavailable', notFoundDescription: 'This page is unavailable; your account data remains safe.', bindingFailed: 'Connection failed. Check the demo link and try again.'
  }
};

// The subset of app/oauth/transaction.js's phase set that actually means
// "show an error banner." Deliberately a closed allowlist, not "everything
// except a couple of known-good phases" -- real bug, 2026-08-20, found live
// via the first real Apple new-account test: App.js's sign-in starter used
// to exclude only 'authenticated'/'profile_required'/'interrupted' and
// treat every other phase as an error, so when account_resolution (a
// legitimate success outcome) was added later, it fell through to the
// generic "failed" copy and rendered an error banner overlapping the
// resolution screen it was transitioning into. A closed list of actual
// error phases can't repeat that failure mode when a new non-error phase
// is added -- it just does nothing until someone deliberately adds it here.
export const oauthErrorPhases = new Set(['failed', 'invalid', 'expired', 'cancelled', 'denied', 'closed']);
