require "securerandom"

module Auth
  class OmniauthController < ActionController::Base
    protect_from_forgery with: :exception
    skip_before_action :verify_authenticity_token

    def callback
      auth_hash = request.env["omniauth.auth"]
      identity = find_or_create_identity(auth_hash)

      establish_account_session!(identity.user)

      if respond_with_json?
        render json: { provider: identity.provider, user_id: identity.user_id }
      else
        redirect_to oauth_redirect_path, notice: "Signed in with #{identity.provider.titleize}."
      end
    rescue StandardError => e
      Rails.logger.error("[OmniauthController] #{e.class}: #{e.message}")
      if respond_with_json?
        render json: { error: "OAuth login failed" }, status: :unprocessable_entity
      else
        redirect_to account_login_path, alert: "OAuth login failed. Please try again."
      end
    end

    def failure
      message = params[:message] || "OAuth failure"
      if respond_with_json?
        render json: { error: message }, status: :unauthorized
      else
        redirect_to account_login_path, alert: message
      end
    end

    private

    def respond_with_json?
      request.format.json?
    end

    def oauth_redirect_path
      request.env["omniauth.origin"].presence || account_dashboard_path
    end

    def establish_account_session!(user)
      reset_session
      session[AppConstants::Sessions.key(:account)] = user.id
    end

    def find_or_create_identity(auth_hash)
      provider = auth_hash["provider"]
      uid = auth_hash["uid"]

      identity = OAuthIdentity.find_or_initialize_by(provider: provider, provider_uid: uid)
      identity.user ||= find_or_create_user(auth_hash)
      identity.email = auth_hash.dig("info", "email")
      identity.credentials = auth_hash["credentials"] || {}
      identity.metadata = {
        info: auth_hash["info"],
        extra: auth_hash["extra"],
        updated_at: Time.current.iso8601
      }
      identity.save!
      ensure_terms_acceptance(identity.user, provider)
      identity
    end

    def find_or_create_user(auth_hash)
      email = auth_hash.dig("info", "email")
      user = User.find_or_initialize_by(email: email.presence || autogenerated_email(auth_hash))
      return user if user.persisted?

      user.assign_attributes(
        english_name: auth_hash.dig("info", "name") || "OAuth User",
        encrypted_password: User.password_hash(SecureRandom.hex(16)),
        metadata: (user.metadata || {}).merge({
          oauth_seeded: true,
          provider: auth_hash["provider"]
        })
      )
      user.save!
      user
    end

    def autogenerated_email(auth_hash)
      "#{auth_hash['provider']}_#{auth_hash['uid']}@#{AppConstants::Project.slug}.oauth"
    end

    def ensure_terms_acceptance(user, provider)
      metadata = (user.metadata || {}).with_indifferent_access
      updated_metadata = metadata.merge(
        signup_source: metadata[:signup_source].presence || provider,
        terms_version: metadata[:terms_version].presence || AppConstants::Legal.default_terms_version,
        terms_accepted_at: metadata[:terms_accepted_at].presence || Time.current.iso8601
      )
      return if updated_metadata == metadata

      user.update!(metadata: updated_metadata)
    end
  end
end
